<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AcmePay.Application\AcmePay.Application.csproj" />
    <ProjectReference Include="..\AcmePay.External\AcmePay.External.csproj" />
    <ProjectReference Include="..\AcmePay.Infrastructure\AcmePay.Infrastructure.csproj" />
  </ItemGroup>

</Project>
