"""initial ai schema

Revision ID: 85d8e55f4bc5
Revises: 
Create Date: 2026-08-15 00:08:00.100869

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '85d8e55f4bc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('incident_id', sa.Text(), nullable=True),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index('ix_ai_documents_path', 'documents', ['project_id', 'path'], unique=False, schema='ai')
    op.create_index('ix_ai_documents_project_type', 'documents', ['project_id', 'document_type'], unique=False, schema='ai')
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('chunk_type', sa.Text(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('incident_id', sa.Text(), nullable=True),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['ai.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index('ix_ai_chunks_document', 'document_chunks', ['document_id'], unique=False, schema='ai')
    op.create_index('ix_ai_chunks_path', 'document_chunks', ['project_id', 'path'], unique=False, schema='ai')
    op.create_index('ix_ai_chunks_project', 'document_chunks', ['project_id'], unique=False, schema='ai')
    # Keyword-search leg: generated tsvector over the 'simple' config (no stemming,
    # so technical identifiers like TimeoutException / JWT / 401 match exactly).
    op.execute(
        """
        ALTER TABLE ai.document_chunks
        ADD COLUMN content_tsv tsvector
        GENERATED ALWAYS AS (to_tsvector('simple', content)) STORED
        """
    )
    op.execute(
        "CREATE INDEX ix_ai_chunks_content_tsv ON ai.document_chunks USING GIN (content_tsv)"
    )
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['ai.document_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', name='uq_ai_embeddings_chunk'),
    schema='ai'
    )
    op.create_index('ix_ai_embeddings_model', 'embeddings', ['model', 'model_version'], unique=False, schema='ai')
    # Vector-search leg: HNSW (cosine) index. Small-data friendly, deterministic ranking.
    op.execute(
        "CREATE INDEX ix_ai_embeddings_vector_hnsw ON ai.embeddings USING hnsw (vector vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ai.ix_ai_embeddings_vector_hnsw')
    op.drop_index('ix_ai_embeddings_model', table_name='embeddings', schema='ai')
    op.drop_table('embeddings', schema='ai')
    op.drop_index('ix_ai_chunks_project', table_name='document_chunks', schema='ai')
    op.drop_index('ix_ai_chunks_path', table_name='document_chunks', schema='ai')
    op.execute('DROP INDEX IF EXISTS ai.ix_ai_chunks_content_tsv')
    op.execute('ALTER TABLE ai.document_chunks DROP COLUMN IF EXISTS content_tsv')
    op.drop_index('ix_ai_chunks_document', table_name='document_chunks', schema='ai')
    op.drop_table('document_chunks', schema='ai')
    op.drop_index('ix_ai_documents_project_type', table_name='documents', schema='ai')
    op.drop_index('ix_ai_documents_path', table_name='documents', schema='ai')
    op.drop_table('documents', schema='ai')
    # ### end Alembic commands ###
